# -*- coding: utf-8 -*-
"""remoteok job scraper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ssansQO9s0fWKPY-L_boR9seuK3gApiC
"""

# ==========================================
# REMOTEOK JSON SCRAPER - GOOGLE COLAB
# ==========================================
# RemoteOK provides a JSON feed - much easier than HTML!

import requests
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import urlparse
import hashlib
import re

def getting_data(keywords, jobs_shown=10):

    jobs_list = []

    try:
        search_term = keywords.lower().replace(' ', '-')
        url = f'https://remoteok.com/api?tag={search_term}'

        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }

        response = requests.get(url, headers=headers)

        data = response.json()

        if len(data) > 1:
            jobs = data[1:]  #u have to skip the first item bc metadata?
        else:
            jobs = []

        # Extract data from each job
        for job in jobs:

             try:

                """
                https://remoteok.com/api?tag=data-science
                position = job title
                min_salary
                """
                # job_id - used url
                #COULD ALSO USE "id":"1128286"
                url = job.get("url") # full url looks like: https://remoteOK.com/remote-jobs/...
                unique_id = urlparse(url).path.split("/")[-1] # get only last part of url
                job_id = hashlib.md5(unique_id.encode("utf-8")).hexdigest() # encode as hash

                # company_name
                company_name = job.get('company', None)

                # title
                title = job.get('position', None)

                # description
                description = job.get('description', None)
                description_clean = re.sub(r"<[^>]*>", "", description)
                description_clean = " ".join(description_clean.split())

                # keywords (cleaned up description)
                keywords = None

                # max_salary
                max_salary = job.get('salary_max', None)

                # location
                location = job.get('location', None)

                # Application URL
                job_url = job.get('url', None)

                job_data = {
                    'job_id': job_id,
                    'company_name': company_name,
                    'title': title,
                    'description': description_clean,
                    'keywords': keywords,
                    'max_salary': max_salary,
                    'location': location,
                    'job_url': job_url
                }

                jobs_list.append(job_data)

             except Exception as e:
                print(f"{e}")
                continue

    except Exception as e:
        print(f"{e}")


    df = pd.DataFrame(jobs_list)

    return df

'''
#RUN UR SCRAPER i hope it works
# - your older brother

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 50)


keywords = "engineer"
jobs_shown = 999999

df = getting_data(keywords, jobs_shown=jobs_shown)

print(df)
'''

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 50)

keywords = 'engineer'
jobs_shown = 10

df = getting_data(keywords, jobs_shown=jobs_shown)

print(df)

engine = create_engine('sqlite:///jobs.db')
df.to_sql('remoteokjobs', engine, if_exists='replace', index=False)